version: "2"

# Build PDF & ePub
formats:
  - htmlzip
  - epub
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py
